namespace CardManagement.Api.Controllers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Card.Application.Commands;
using Card.Application.DTOs;
using Shared.Facades;
using FluentValidation;
using System.Security.Claims;

[Authorize]
[ApiController]
[Route("api/[controller]")]
public class CardsController : ControllerBase
{
    private readonly ICardFacade _cardFacade;
    private readonly IValidator<CreateCardCommand> _createCardValidator;
    private readonly IValidator<UpdateCardCommand> _updateCardValidator;

    public CardsController(
        ICardFacade cardFacade,
        IValidator<CreateCardCommand> createCardValidator,
        IValidator<UpdateCardCommand> updateCardValidator)
    {
        _cardFacade = cardFacade;
        _createCardValidator = createCardValidator;
        _updateCardValidator = updateCardValidator;
    }

    /// <summary>
    /// Retrieves all credit cards belonging to the authenticated user
    /// </summary>
    /// <remarks>
    /// Returns a list of all cards owned by the current authenticated user.
    /// User authentication is determined via JWT token.
    /// </remarks>
    /// <response code="200">Returns the list of user's cards</response>
    /// <response code="401">If the user is not authenticated</response>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> GetUserCards()
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null || !Guid.TryParse(userIdClaim, out var userId))
        {
            return Unauthorized();
        }

        var cards = await _cardFacade.GetUserCardsAsync(userId);
        return Ok(cards);
    }

    /// <summary>
    /// Retrieves details of a specific credit card by its ID
    /// </summary>
    /// <remarks>
    /// Returns detailed information about a card. Only the card owner can access this information.
    /// </remarks>
    /// <param name="id">The unique identifier of the card</param>
    /// <response code="200">Returns the card details</response>
    /// <response code="401">If the user is not authenticated</response>
    /// <response code="403">If the card doesn't belong to the authenticated user</response>
    /// <response code="404">If the card is not found</response>
    [HttpGet("{id}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetCard(Guid id)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null || !Guid.TryParse(userIdClaim, out var userId))
        {
            return Unauthorized();
        }

        var card = await _cardFacade.GetCardDetailAsync(id);
        if (card == null)
        {
            return NotFound(new { message = "Card not found" });
        }

        // Verify the card belongs to the user
        var belongsToUser = await _cardFacade.CardBelongsToUserAsync(id, userId);
        if (!belongsToUser)
        {
            return Forbid();
        }

        return Ok(card);
    }

    /// <summary>
    /// Creates a new credit card for the authenticated user
    /// </summary>
    /// <remarks>
    /// Creates and activates a new card. The card number is automatically generated by the bank using:
    /// - BIN (Bank Identification Number): 4532 (Visa)
    /// - Random account digits
    /// - Luhn algorithm check digit for validation
    /// The card is automatically associated with the authenticated user.
    /// Expiration date is automatically set to 5 years from the creation date (last day of month).
    /// </remarks>
    /// <param name="request">Card creation data including holder name and credit limit (max $300,000 COP). Users can have maximum 3 active cards</param>
    /// <response code="201">Card created successfully. Returns the created card details with generated card number</response>
    /// <response code="400">If validation fails or card data is invalid</response>
    /// <response code="401">If the user is not authenticated</response>
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    public async Task<IActionResult> CreateCard([FromBody] CreateCardRequest request)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null || !Guid.TryParse(userIdClaim, out var userId))
        {
            return Unauthorized();
        }

        var command = new CreateCardCommand
        {
            UserId = userId,
            HolderName = request.HolderName,
            CreditLimit = request.CreditLimit
        };

        var validationResult = await _createCardValidator.ValidateAsync(command);
        if (!validationResult.IsValid)
        {
            return BadRequest(new { errors = validationResult.Errors.Select(e => e.ErrorMessage) });
        }

        try
        {
            var cardId = await _cardFacade.CreateCardAsync(
                userId,
                command.HolderName,
                command.CreditLimit);

            var createdCard = await _cardFacade.GetCardDetailAsync(cardId);
            return CreatedAtAction(nameof(GetCard), new { id = cardId }, createdCard);
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    /// <summary>
    /// Updates information of an existing credit card
    /// </summary>
    /// <remarks>
    /// Allows updating the cardholder name and expiration date.
    /// Only the card owner can perform this operation.
    /// Note: Card number and credit limit cannot be modified.
    /// </remarks>
    /// <param name="id">The unique identifier of the card to update</param>
    /// <param name="request">Updated card data (holder name and expiration date)</param>
    /// <response code="200">Card updated successfully. Returns the updated card details</response>
    /// <response code="400">If validation fails or update data is invalid</response>
    /// <response code="401">If the user is not authenticated</response>
    /// <response code="403">If the card doesn't belong to the authenticated user</response>
    [HttpPut("{id}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public async Task<IActionResult> UpdateCard(Guid id, [FromBody] UpdateCardRequest request)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null || !Guid.TryParse(userIdClaim, out var userId))
        {
            return Unauthorized();
        }

        var belongsToUser = await _cardFacade.CardBelongsToUserAsync(id, userId);
        if (!belongsToUser)
        {
            return Forbid();
        }

        var command = new UpdateCardCommand
        {
            CardId = id,
            HolderName = request.HolderName,
            CreditLimit = request.CreditLimit
        };

        var validationResult = await _updateCardValidator.ValidateAsync(command);
        if (!validationResult.IsValid)
        {
            return BadRequest(new { errors = validationResult.Errors.Select(e => e.ErrorMessage) });
        }

        try
        {
            await _cardFacade.UpdateCardAsync(id, command.HolderName, command.CreditLimit);
            var updatedCard = await _cardFacade.GetCardDetailAsync(id);
            return Ok(updatedCard);
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    /// <summary>
    /// Deletes a credit card permanently
    /// </summary>
    /// <remarks>
    /// Permanently removes a card from the system.
    /// Only the card owner can perform this operation.
    /// Warning: This action cannot be undone.
    /// </remarks>
    /// <param name="id">The unique identifier of the card to delete</param>
    /// <response code="204">Card deleted successfully (No Content)</response>
    /// <response code="400">If deletion fails</response>
    /// <response code="401">If the user is not authenticated</response>
    /// <response code="403">If the card doesn't belong to the authenticated user</response>
    [HttpDelete("{id}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status403Forbidden)]
    public async Task<IActionResult> DeleteCard(Guid id)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null || !Guid.TryParse(userIdClaim, out var userId))
        {
            return Unauthorized();
        }

        var belongsToUser = await _cardFacade.CardBelongsToUserAsync(id, userId);
        if (!belongsToUser)
        {
            return Forbid();
        }

        try
        {
            await _cardFacade.DeleteCardAsync(id);
            return NoContent();
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }
}
